INSERT INTO game_format (name)
VALUES ('none'),
       ('Standard'),
       ('Pioneer'),
       ('Modern'),
       ('Legacy'),
       ('Vintage'),
       ('Pauper'),
       ('Sealed Deck'),
       ('Booster Draft'),
       ('Commander'),
       ('Duel Commander'),
       ('cEDH'),
       ('Pauper Commander'),
       ('Oathbreaker'),
       ('Brawl'),
       ('Historic'),
       ('Explorer'),
       ('Alchemy'),
       ('Timeless'),
       ('Two-Headed Giant'),
       ('Planechase'),
       ('Archenemy'),
       ('Conspiracy'),
       ('Commander Box League'),
       ('Commander Two-Headed Giant');
